platform :ios, '10.3'

target 'OneSignalDemo' do
  pod 'OneSignal', :path => '~/Documents/GitHub/OneSignal-iOS-SDK'
end

target 'NotificationServiceExtension' do
  pod 'OneSignal', :path => '~/Documents/GitHub/OneSignal-iOS-SDK'
end

